version: '3.8'
services:
  postgresql:
    image: postgres
    container_name: postgres_countries
    restart: always
    environment:
      POSTGRES_DB: countries_dev
      POSTGRES_HOST: localhost
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_ROOT_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"